import type { Task, Team, User } from "./types"

export const CURRENT_USER_ID = "u1"

export const USERS: User[] = [
  { id: "u1", name: "Indal Yadav", email: "indal@meetspace.app", initials: "IY", color: "#6366f1", role: "Product Lead" },
  { id: "u2", name: "Maya Chen", email: "maya@meetspace.app", initials: "MC", color: "#8b5cf6", role: "Design Lead" },
  { id: "u3", name: "Arjun Patel", email: "arjun@meetspace.app", initials: "AP", color: "#0ea5e9", role: "Frontend Engineer" },
  { id: "u4", name: "Sofia Rossi", email: "sofia@meetspace.app", initials: "SR", color: "#f43f5e", role: "Product Manager" },
  { id: "u5", name: "Leo Nakamura", email: "leo@meetspace.app", initials: "LN", color: "#10b981", role: "Backend Engineer" },
  { id: "u6", name: "Priya Sharma", email: "priya@meetspace.app", initials: "PS", color: "#f59e0b", role: "Product Designer" },
  { id: "u7", name: "Daniel Kim", email: "daniel@meetspace.app", initials: "DK", color: "#06b6d4", role: "QA Engineer" },
  { id: "u8", name: "Hannah Weber", email: "hannah@meetspace.app", initials: "HW", color: "#d946ef", role: "Growth Marketer" },
]

export const TEAMS: Team[] = [
  {
    id: "t-eng",
    name: "Engineering",
    key: "ENG",
    description: "Ships the platform, APIs, and infrastructure that everything else runs on.",
    color: "#6366f1",
    icon: "💻",
    memberIds: ["u1", "u3", "u5", "u7"],
    leadId: "u3",
    createdAt: "2025-11-02",
  },
  {
    id: "t-design",
    name: "Design",
    key: "DSN",
    description: "Owns the product experience, design system, and brand.",
    color: "#8b5cf6",
    icon: "🎨",
    memberIds: ["u2", "u6"],
    leadId: "u2",
    createdAt: "2025-11-05",
  },
  {
    id: "t-product",
    name: "Product",
    key: "PRD",
    description: "Sets the roadmap, writes specs, and keeps everyone pointed the same way.",
    color: "#f43f5e",
    icon: "🧭",
    memberIds: ["u1", "u4", "u2"],
    leadId: "u4",
    createdAt: "2025-11-02",
  },
  {
    id: "t-growth",
    name: "Growth",
    key: "GRW",
    description: "Acquisition, lifecycle, and everything that moves the funnel.",
    color: "#10b981",
    icon: "📈",
    memberIds: ["u8", "u4"],
    leadId: "u8",
    createdAt: "2026-01-14",
  },
]

export const TASKS: Task[] = [
  {
    id: "k1", key: "ENG-128", title: "Build real-time task board with optimistic updates",
    description: "Drag-and-drop board where moving a card updates status instantly and syncs in the background. Should feel snappy even on slow connections.",
    status: "in_progress", priority: "high", assigneeIds: ["u3", "u1"], teamId: "t-eng",
    tags: ["feature", "infra"], dueDate: "2026-06-12",
    subtasks: [
      { id: "s1", title: "Column drag targets", done: true },
      { id: "s2", title: "Optimistic status mutation", done: true },
      { id: "s3", title: "Reconcile on server response", done: false },
      { id: "s4", title: "Keyboard reordering", done: false },
    ],
    comments: [
      { id: "c1", authorId: "u1", body: "Let's make sure the empty column drop target is generous — easy to miss otherwise.", createdAt: "2026-06-05T09:20:00Z" },
      { id: "c2", authorId: "u3", body: "Agreed. Padding bumped to 64px when a card is being dragged.", createdAt: "2026-06-05T11:02:00Z" },
    ],
    createdAt: "2026-05-28", updatedAt: "2026-06-06",
  },
  {
    id: "k2", key: "ENG-131", title: "Rate-limit the public API gateway",
    description: "Add token-bucket rate limiting per API key with sensible defaults and clear 429 responses.",
    status: "todo", priority: "urgent", assigneeIds: ["u5"], teamId: "t-eng",
    tags: ["infra", "bug"], dueDate: "2026-06-09",
    subtasks: [
      { id: "s5", title: "Token bucket middleware", done: false },
      { id: "s6", title: "Per-key config store", done: false },
    ],
    comments: [], createdAt: "2026-06-01", updatedAt: "2026-06-04",
  },
  {
    id: "k3", key: "ENG-117", title: "Migrate auth sessions to edge-cached tokens",
    description: "Move session validation to the edge to cut p95 latency on authenticated routes.",
    status: "in_review", priority: "medium", assigneeIds: ["u5", "u7"], teamId: "t-eng",
    tags: ["infra"], dueDate: "2026-06-10",
    subtasks: [{ id: "s7", title: "Edge token verifier", done: true }, { id: "s8", title: "Rollback plan", done: true }],
    comments: [{ id: "c3", authorId: "u7", body: "QA passed in staging. One flaky test around clock skew — re-running.", createdAt: "2026-06-06T14:10:00Z" }],
    createdAt: "2026-05-20", updatedAt: "2026-06-06",
  },
  {
    id: "k4", key: "ENG-140", title: "Fix avatar upload crash on Safari",
    description: "Uploading a HEIC image on Safari throws and loses the form state. Convert client-side before upload.",
    status: "backlog", priority: "high", assigneeIds: ["u3"], teamId: "t-eng",
    tags: ["bug"], dueDate: null, subtasks: [], comments: [],
    createdAt: "2026-06-03", updatedAt: "2026-06-03",
  },
  {
    id: "k5", key: "ENG-101", title: "Set up end-to-end test pipeline",
    description: "Playwright suite running on every PR with sharded parallel execution.",
    status: "done", priority: "medium", assigneeIds: ["u7", "u3"], teamId: "t-eng",
    tags: ["infra", "docs"], dueDate: "2026-05-30",
    subtasks: [{ id: "s9", title: "Playwright config", done: true }, { id: "s10", title: "CI sharding", done: true }, { id: "s11", title: "Flake retry policy", done: true }],
    comments: [], createdAt: "2026-05-10", updatedAt: "2026-05-29",
  },
  {
    id: "k6", key: "ENG-145", title: "Webhook delivery retries with backoff",
    description: "Outbound webhooks should retry with exponential backoff and surface a delivery log.",
    status: "backlog", priority: "low", assigneeIds: ["u5"], teamId: "t-eng",
    tags: ["feature", "infra"], dueDate: "2026-06-24", subtasks: [], comments: [],
    createdAt: "2026-06-04", updatedAt: "2026-06-04",
  },
  {
    id: "k7", key: "ENG-150", title: "Dark mode token audit",
    description: "Sweep for hardcoded colors that break in dark mode and replace with semantic tokens.",
    status: "todo", priority: "low", assigneeIds: ["u1"], teamId: "t-eng",
    tags: ["ux", "design"], dueDate: "2026-06-18", subtasks: [],
    comments: [], createdAt: "2026-06-05", updatedAt: "2026-06-05",
  },

  {
    id: "k8", key: "DSN-064", title: "Redesign the task detail panel",
    description: "Cleaner hierarchy: title, status, and assignees up top, activity at the bottom. Reduce visual noise.",
    status: "in_progress", priority: "high", assigneeIds: ["u2", "u6"], teamId: "t-design",
    tags: ["design", "ux"], dueDate: "2026-06-11",
    subtasks: [{ id: "s12", title: "Low-fi wireframes", done: true }, { id: "s13", title: "Hi-fi mockups", done: true }, { id: "s14", title: "Dev handoff", done: false }],
    comments: [{ id: "c4", authorId: "u2", body: "Moved activity into a collapsible section to keep the fold focused on the essentials.", createdAt: "2026-06-05T16:40:00Z" }],
    createdAt: "2026-05-26", updatedAt: "2026-06-06",
  },
  {
    id: "k9", key: "DSN-070", title: "Design system: status & priority components",
    description: "Define the canonical status pills and priority flags, plus dark-mode variants.",
    status: "in_review", priority: "medium", assigneeIds: ["u6"], teamId: "t-design",
    tags: ["design"], dueDate: "2026-06-08",
    subtasks: [{ id: "s15", title: "Status tokens", done: true }, { id: "s16", title: "Priority flags", done: true }],
    comments: [], createdAt: "2026-05-22", updatedAt: "2026-06-06",
  },
  {
    id: "k10", key: "DSN-058", title: "Empty states illustration set",
    description: "Friendly empty states for board, list, and search with no results.",
    status: "done", priority: "low", assigneeIds: ["u6"], teamId: "t-design",
    tags: ["design", "ux"], dueDate: "2026-05-28", subtasks: [], comments: [],
    createdAt: "2026-05-08", updatedAt: "2026-05-27",
  },
  {
    id: "k11", key: "DSN-075", title: "Onboarding flow exploration",
    description: "First-run experience that gets a new team to their first task in under two minutes.",
    status: "todo", priority: "medium", assigneeIds: ["u2"], teamId: "t-design",
    tags: ["ux", "research"], dueDate: "2026-06-20", subtasks: [], comments: [],
    createdAt: "2026-06-02", updatedAt: "2026-06-02",
  },
  {
    id: "k12", key: "DSN-080", title: "Icon set refresh",
    description: "Replace mismatched icons with a single consistent family across the app.",
    status: "backlog", priority: "none", assigneeIds: ["u6"], teamId: "t-design",
    tags: ["design"], dueDate: null, subtasks: [], comments: [],
    createdAt: "2026-06-04", updatedAt: "2026-06-04",
  },

  {
    id: "k13", key: "PRD-042", title: "Q3 roadmap draft",
    description: "Synthesize feedback and analytics into a prioritized Q3 roadmap for review.",
    status: "in_progress", priority: "urgent", assigneeIds: ["u4", "u1"], teamId: "t-product",
    tags: ["docs", "research"], dueDate: "2026-06-13",
    subtasks: [{ id: "s17", title: "Pull usage data", done: true }, { id: "s18", title: "Theme the asks", done: false }, { id: "s19", title: "Draft narrative", done: false }],
    comments: [{ id: "c5", authorId: "u4", body: "Top requests are bulk edits and saved filters. Let's slot both into the first half.", createdAt: "2026-06-06T08:15:00Z" }],
    createdAt: "2026-05-30", updatedAt: "2026-06-06",
  },
  {
    id: "k14", key: "PRD-039", title: "Write spec for saved filters",
    description: "Let users name and pin filter combinations. Define sharing and permissions.",
    status: "todo", priority: "high", assigneeIds: ["u4"], teamId: "t-product",
    tags: ["docs", "feature"], dueDate: "2026-06-16", subtasks: [], comments: [],
    createdAt: "2026-06-01", updatedAt: "2026-06-03",
  },
  {
    id: "k15", key: "PRD-031", title: "Competitive teardown: task tools",
    description: "How do the incumbents handle teams + tasks? Find the gaps we can own.",
    status: "done", priority: "medium", assigneeIds: ["u1"], teamId: "t-product",
    tags: ["research"], dueDate: "2026-05-25", subtasks: [], comments: [],
    createdAt: "2026-05-12", updatedAt: "2026-05-24",
  },
  {
    id: "k16", key: "PRD-048", title: "Define team roles & permissions model",
    description: "Owner, admin, member, guest — what each can see and do across teams.",
    status: "backlog", priority: "high", assigneeIds: ["u4", "u1"], teamId: "t-product",
    tags: ["docs"], dueDate: "2026-06-26", subtasks: [], comments: [],
    createdAt: "2026-06-05", updatedAt: "2026-06-05",
  },
  {
    id: "k17", key: "PRD-052", title: "User interviews: how teams plan their week",
    description: "Five interviews to understand weekly planning rituals and where they break.",
    status: "in_review", priority: "low", assigneeIds: ["u4"], teamId: "t-product",
    tags: ["research"], dueDate: "2026-06-10", subtasks: [], comments: [],
    createdAt: "2026-05-27", updatedAt: "2026-06-06",
  },

  {
    id: "k18", key: "GRW-021", title: "Launch announcement landing page",
    description: "A focused landing page for the public launch with a single, clear call to action.",
    status: "in_progress", priority: "high", assigneeIds: ["u8"], teamId: "t-growth",
    tags: ["growth", "design"], dueDate: "2026-06-14",
    subtasks: [{ id: "s20", title: "Copy draft", done: true }, { id: "s21", title: "Hero design", done: false }],
    comments: [], createdAt: "2026-05-29", updatedAt: "2026-06-05",
  },
  {
    id: "k19", key: "GRW-018", title: "Lifecycle email sequence",
    description: "Five-email onboarding sequence triggered on signup, with activation milestones.",
    status: "todo", priority: "medium", assigneeIds: ["u8", "u4"], teamId: "t-growth",
    tags: ["growth"], dueDate: "2026-06-19", subtasks: [], comments: [],
    createdAt: "2026-06-02", updatedAt: "2026-06-02",
  },
  {
    id: "k20", key: "GRW-009", title: "Set up product analytics events",
    description: "Instrument the core funnel: signup → first team → first task → invite.",
    status: "done", priority: "high", assigneeIds: ["u8", "u5"], teamId: "t-growth",
    tags: ["growth", "infra"], dueDate: "2026-05-31", subtasks: [], comments: [],
    createdAt: "2026-05-15", updatedAt: "2026-05-30",
  },
  {
    id: "k21", key: "GRW-024", title: "Referral program experiment",
    description: "Test a give-one-get-one referral loop with a holdout group.",
    status: "backlog", priority: "low", assigneeIds: ["u8"], teamId: "t-growth",
    tags: ["growth", "research"], dueDate: null, subtasks: [], comments: [],
    createdAt: "2026-06-04", updatedAt: "2026-06-04",
  },
  {
    id: "k22", key: "ENG-152", title: "Bulk edit selected tasks",
    description: "Multi-select on the list view to change status, assignee, or priority in one action.",
    status: "todo", priority: "high", assigneeIds: ["u3", "u1"], teamId: "t-eng",
    tags: ["feature"], dueDate: "2026-06-17", subtasks: [], comments: [],
    createdAt: "2026-06-06", updatedAt: "2026-06-06",
  },
  {
    id: "k23", key: "DSN-082", title: "Accessibility pass on the board",
    description: "Keyboard navigation, focus rings, and color-contrast on status pills.",
    status: "todo", priority: "medium", assigneeIds: ["u6", "u7"], teamId: "t-design",
    tags: ["ux", "design"], dueDate: "2026-06-21", subtasks: [], comments: [],
    createdAt: "2026-06-06", updatedAt: "2026-06-06",
  },
  {
    id: "k24", key: "PRD-055", title: "Pricing & packaging research",
    description: "Per-seat vs per-team pricing — model both against the funnel data.",
    status: "in_progress", priority: "medium", assigneeIds: ["u4"], teamId: "t-product",
    tags: ["research", "growth"], dueDate: "2026-06-15", subtasks: [], comments: [],
    createdAt: "2026-06-03", updatedAt: "2026-06-05",
  },
]
